tempCalculate: temperature.o lab_10_unit_test.o
	g++ -Wall -g -o tempCalc temperature.o lab_10_unit_test.o
	
lab10unittest:lab_10_unit_test.cpp
	g++ -Wall -g -c lab_10_unit_test.cpp
	
tempCalc: temperature.cpp
	g++ -Wall -g -c temperature.cpp
	