allOfIt:	lab_25_unit_test.o bst_node.o bs_tree.o
	g++ -Wall -g -o BSTree lab_25_unit_test.o bs_tree.o bst_node.o
	
lab24unittest:	lab_25_unit_test.cpp
	g++ -Wall -g -c lab_25_unit_test.cpp
	
BSTNode:	bst_node.cpp
	g++ -Wall -g -c bst_node.cpp
	
BSTree:	bs_tree.cpp
	g++ -Wall -g -c bs_tree.cpp
	