allOfIt:	lab_15_unit_test.o sorting.o
	g++ -Wall -g -o Sorting lab_15_unit_test.o sorting.o
	
lab26unittest:	lab_15_unit_test.cpp
	g++ -Wall -g -c lab_15_unit_test.cpp
	
Sorting:	sorting.cpp
	g++ -Wall -g -c sorting.cpp
	
