allOfIt:	lab_18_unit_test.o sl_list.o sl_node.o
	g++ -Wall -g -o Slist sl_list.o lab_18_unit_test.o sl_node.o
	
lab17unittest:	lab_18_unit_test.cpp
	g++ -Wall -g -c lab_18_unit_test.cpp
	
Slist:	sl_list.cpp
	g++ -Wall -g -c sl_list.cpp
	
Node:	sl_node.cpp
	g++ -Wall -g -c sl_node.cpp
	