allOfIt:	lab_17_unit_test.o sl_node.o
	g++ -Wall -g -o Node sl_node.o lab_17_unit_test.o
	
lab17unittest:	lab_17_unit_test.cpp
	g++ -Wall -g -c lab_17_unit_test.cpp
	
Node:	sl_node.cpp
	g++ -Wall -g -c sl_node.cpp
	