moneyCalculate: money.o lab_11_unit_test.o
	g++ -Wall -g -o moneyCalc money.o lab_11_unit_test.o
	
lab11unittest:lab_11_unit_test.cpp
	g++ -Wall -g -c lab_11_unit_test.cpp
	
moneyCalc: money.cpp
	g++ -Wall -g -c money.cpp
	