theLab: lab_12.o lab_12_unit_test.o
	g++ -Wall -g -o arrays lab_12.o lab_12_unit_test.o
	
lab13unittest:lab_12_unit_test.cpp
	g++ -Wall -g -c lab_12_unit_test.cpp
	
arrays: lab_12.cpp
	g++ -Wall -g -c lab_12.cpp
	