allOfIt:	item.o lab_12_unit_test.o food_item.o magic_item.o
	g++ -Wall -g -o Items Food Magic item.o lab_12_unit_test.o food_item.o magic_item.o
	
lab12unittest:	lab_12_unit_test.cpp
	g++ -Wall -g -c lab_12_unit_test.cpp
	
Items:	item.cpp
	g++ -Wall -g -c item.cpp
	
Food:	food_item.cpp
	g++ -Wall -g -c food_item.cpp
	
Magic:	magic_item.cpp
	g++ -Wall -g -c magic_item.cpp
	