allOfIt:	lab_23_unit_test.o bst_node.o
	g++ -Wall -g -o BSTNode bst_node.o lab_23_unit_test.o
	
lab23unittest:	lab_23_unit_test.cpp
	g++ -Wall -g -c lab_23_unit_test.cpp
	
BSTNode:	bst_node.cpp
	g++ -Wall -g -c bst_node.cpp
	